name: care_senior_study
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  flutter_svg: ^2.3.0
  google_fonts: ^8.2.1
  camera: ^0.12.0+2
  google_maps_flutter: ^2.18.0
  intl: ^0.20.3
  url_launcher: ^6.3.1
  file_picker: ^11.0.3
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
